export const INPUT_CHANGE = 'INPUT_CHANGE'
export const ADD_LIST = 'ADD_LIST'
export const DEL_ITEM = 'DEL_ITEM'
export const GET_LIST = 'GET_LIST'
export const TEST_THUNK = 'TEST_THUNK'
export const TEST_SAGA = 'TEST_SAGA'